fullnameOverride: "landing-prod"
nameOverride: "landing-prod"
image:
  repository: ghcr.io/green-ecolution/project-website
  tag: v1.3.1
  pullPolicy: Always
ingress:
  hosts:
    - green-ecolution.de
    - green-ecolution.io
    - green-ecolution.dev
    - green-ecolution.com
    - green-ecolution.net
  addWww: true
